version: "3"

services:

  consumerapp:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - consumerapp-mysql
      - consumerapp-redis

  consumerapp-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: consumerapp
      MYSQL_ROOT_PASSWORD: root

  consumerapp-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - consumerapp

  consumerapp-redis:
    image: redis:alpine
    expose:
      - 6379

